language: node_js

node_js:
  - "stable"

before_install:
  # add id_rsa private key
  - openssl aes-256-cbc -K $encrypted_c2697660bfd7_key -iv $encrypted_c2697660bfd7_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.name "billryan"
  - git config --global user.email yuanbin2014@gmail.com
  # update first
  - sudo apt-get update -qq
  # Install Gitbook
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - cd ~
  - git clone git@github.com:billryan/algorithm-exercise.git
  - cp algorithm-exercise/scripts/rename_ebook.sh ~/
  - chmod +x rename_ebook.sh

before_script:
  # install calibre latest version
  - sudo -v && wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

script:
  - mkdir -p ~/upload
  # install source code pro
  - mkdir -p ~/fonts
  - cd ~/fonts
  - wget https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKSC-hinted.zip
  - wget https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKTC-hinted.zip
  - unzip -o NotoSansCJKSC-hinted.zip
  - unzip -o NotoSansCJKTC-hinted.zip
  - mkdir -p ~/.fonts/noto
  - mv *.otf ~/.fonts/noto
  - mkdir -p ~/.fonts/fontconfig/conf.d/
  - cp ~/algorithm-exercise/conf/20-noto-cjk.conf ~/.fonts/fontconfig/conf.d/
  - sudo fc-cache -f -v
  # gitbook build
  - cd ~/algorithm-exercise/
  - gitbook install && gitbook build .
  - gitbook pdf .
  - gitbook epub .
  - gitbook mobi .
  - mv *.pdf *.epub *.mobi ~/upload
  - cd ~/upload
  - sh ~/rename_ebook.sh

after_success:
  - cd ~/algorithm-exercise
  - git remote add gitcafe git@gitcafe.com:billryan/algorithm-exercise.git
  - git push -u gitcafe HEAD:master --force
  - git checkout deploy
  - cp ~/upload/*.epub epub
  - cp ~/upload/*.pdf pdf
  - cp ~/upload/*.mobi mobi
  - git add epub
  - git add pdf
  - git add mobi
  - git commit --amend -m "Updated $(date)"
  - git push -u gitcafe HEAD:deploy --force
  - git push -u origin HEAD:deploy --force

# blacklist
branches:
  except:
    - deploy

# whitelist
branches:
  only:
    - master
